spring:
  application:
    name: MY_Goal_Optimizer

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 16
        max-idle: 32
        min-idle: 8

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  profiles:
    active: secret

server:
  port: 8080
